!obj:pylearn2.train.Train {
  dataset: &train !obj:pylearn2.datasets.csv_dataset.CSVDataset {
    path: '../Data/train_pylearn2.csv',
    task: 'classification',
    start_fraction: .8
  }
  ,
  model: !obj:pylearn2.models.softmax_regression.SoftmaxRegression {
    n_classes: 9,
    irange: .05,
    nvis: 93
  }
  ,
  algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
    batch_size: 5000,
    line_search_mode: 'exhaustive',
    conjugate: 1,
    monitoring_dataset: {
      'train': *train,
      'valid': !obj:pylearn2.datasets.csv_dataset.CSVDataset {
        path: '../Data/train_pylearn2.csv',
        task: 'classification',
        end_fraction: .2
      }
    },
    termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
      channel_name: 'valid_y_misclass'
    }
  }
}
