!obj:pylearn2.train.Train {
  dataset: &train !obj:pylearn2.datasets.csv_dataset.CSVDataset {
    path: '../../Data/train_pylearn2.csv',
    task: 'classification',
    start_fraction: .8
  }
  ,
  model: !obj:pylearn2.models.mlp.MLP {
    layers: [
      !obj:pylearn2.models.mlp.PretrainedLayer {
        layer_name: 'h0',
        layer_content: !pkl: "./dae_l1.pkl",
      },
      !obj:pylearn2.models.mlp.PretrainedLayer {
        layer_name: 'h1',
        layer_content: !pkl: "./dae_l2.pkl",
      },
      !obj:pylearn2.models.mlp.Softmax {
        layer_name: 'y',
        n_classes: 9,
        irange: 0.05
      }
    ],
    nvis: 93
  }
  ,
  algorithm: !obj:pylearn2.training_algorithms.bgd.BGD {
    batch_size: 8192,
    line_search_mode: 'exhaustive',
    conjugate: 1,
    updates_per_batch: 10,
    monitoring_dataset: {
      'train': *train,
      'valid': !obj:pylearn2.datasets.csv_dataset.CSVDataset {
        path: '../../Data/train_pylearn2.csv',
        task: 'classification',
        end_fraction: .2
      }
    },
    termination_criterion: !obj:pylearn2.termination_criteria.And {
      criteria: [
        !obj:pylearn2.termination_criteria.MonitorBased {
          channel_name: "valid_objective",
          prop_decrease: .001,
          N: 10,
        },
        !obj:pylearn2.termination_criteria.EpochCounter {
          max_epochs: 10000
        }
      ]
    }
  },
  extensions: [
    !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
      channel_name: 'valid_y_misclass',
      save_path: 'mlp_best.pkl'
    },
  ]
}
